name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: uv sync --dev
      
    - name: Run tests with pytest
      run: uv run pytest test/ -v
    
    - name: Test package build
      run: uv build
    
    - name: Test package installation
      run: |
        # Test that the built package can be installed (start server in background and test)
        uvx --from ./dist/credential_manager_mcp-*.whl credential-manager-mcp &
        SERVER_PID=$!
        sleep 10
        kill $SERVER_PID 2>/dev/null || true
        echo "✅ Package installation test completed (server started successfully)"
      
    - name: Check if server starts
      run: |
        # Test if the server can start (background process with timeout)
        uv run credential-manager-mcp &
        SERVER_PID=$!
        sleep 5
        kill $SERVER_PID 2>/dev/null || true
        echo "✅ Server startup test completed"
